import * as fs from 'fs';
import * as path from 'path';

export interface ValidationCheck {
  status: 'pass' | 'fail' | 'skipped';
  message: string;
  metrics?: any;
  artifactPath?: string;
}

export interface EvidenceManifest {
  module: string;
  commit: string;
  generatedAt: string;
  certificationVersion: string;
  toolVersions: {
    node: string;
    prisma?: string;
    jest?: string;
    stryker?: string;
  };
  checks: Record<string, ValidationCheck>;
}

export async function generateEvidenceIndex(moduleName: string, manifest: EvidenceManifest) {
  const dateStr = new Date().toISOString().split('T')[0];
  const evidenceDir = path.join(process.cwd(), 'evidence', moduleName, dateStr);
  const docsDir = path.join(process.cwd(), 'docs', 'modules', moduleName);

  fs.mkdirSync(evidenceDir, { recursive: true });
  fs.mkdirSync(docsDir, { recursive: true });

  // Generate JSON Manifest
  const jsonContent = JSON.stringify(manifest, null, 2);
  fs.writeFileSync(path.join(evidenceDir, 'manifest.json'), jsonContent);
  fs.writeFileSync(path.join(docsDir, 'manifest.json'), jsonContent);

  // Generate Markdown
  let mdChecks = '';
  for (const [checkName, result] of Object.entries(manifest.checks)) {
    const icon = result.status === 'pass' ? '🟢' : (result.status === 'skipped' ? '⚪' : '🔴');
    mdChecks += `- **${checkName}**: ${icon} ${result.status.toUpperCase()} - ${result.message}\n`;
    if (result.artifactPath) {
      mdChecks += `  - Artifact: [Link](${result.artifactPath})\n`;
    }
  }

  const mdContent = `# Evidence Manifest: ${moduleName.toUpperCase()}
Generated on: ${manifest.generatedAt}
Commit: ${manifest.commit}
Certification Version: ${manifest.certificationVersion}

## Status Checks
${mdChecks}

*This file is automatically generated by the Platform Verification Infrastructure. Do not edit manually.*
`;

  fs.writeFileSync(path.join(evidenceDir, 'MODULE_EVIDENCE_INDEX.md'), mdContent);
  fs.writeFileSync(path.join(docsDir, 'MODULE_EVIDENCE_INDEX.md'), mdContent);

  return { evidenceDir, mdContent };
}
